### ISSUE TITLE
Gitlab Support ?

### ISSUE THREAD

**Issue by qlaffont** [AkashRajpurohit/git-sync#1]
### Describe the feature or enhancement

Hello,
First of all, your project is awesome ! Do you think is it possible to add Gitlab ? :) 
Thanks !

**Comment by AkashRajpurohit** [comment]
Hey, thanks for opening this, I don't have it planned for other platforms like Bitbucket and Gitlab as of now, but if there is interest for supporting more platforms then I would be happy to look into those as well.

Additionally, if you want to extend the functionality then please feel free to do it and PRs are welcomed for the same.

For now, I will keep this open for other users to vote to understand if there is more interest towards it.

**Comment by AkashRajpurohit** [comment]
Hey @qlaffont the version [0.5.0](https://github.com/AkashRajpurohit/git-sync/releases/tag/v0.5.0) adds support for Gitlab now, Since I don't use Gitlab that much, I have done some basic testing, and it seems to be working fine, can you verify it for your workflows?
Feel free to report any issues if you encounter them.

**Comment by qlaffont** [comment]
@AkashRajpurohit to be honest I have migrated all my projects recently in github, so i can't test ^^" Let's wait an issue
